import { Inter } from "next/font/google";
import Navbar from "../components/nav/Navbar";
import Footer from "../components/nav/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "dennime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`bg-Background ${inter.className}`}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
